spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: webengineering

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              org.springframework.data.mongodb.core.MongoTemplate: INFO

configuration:
  swagger:
    mail: 'becir.isakovic@ibu.edu.ba' # TODO read this in the swagger config file