spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: webengineering

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              org.springframework.data.mongodb.core.MongoTemplate: INFO

email:
  mailgun:
    from-email: Excited User <mailgun@sandboxe07bbd31526745b3a36d99843ba35ff6.mailgun.org>
    username: api
    password: key-1eb78e83ef72914b3c27ff20bfbde91e-3750a53b-77aac5f7

security:
  basic:
    enabled: false
  jwt:
    secret: 'mXLjT3Gm4skNsCdntWodbHPb1GqY35fGVaisLwImIp8cLZP7W6'

management:
  security:
    enabled: false